services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/priguli.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/priguli.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production